import { NextAuthProvider } from './components/Providers';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <head />
            <body>
                <NextAuthProvider>
                    <div className='bg-blue-900 min-h-screen flex'>
                        {children}
                    </div>
                </NextAuthProvider>
            </body>
        </html>
    );
}
